name: framedrop Upload Pipeline
on:
  pull_request:
    types:
      - closed
    branches:
      - 'develop'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Unit Tests with Maven
        env:
          ACCESS_KEY_TEST: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_KEY_TEST: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: mvn -B test -Dspring.profiles.active=test
        working-directory: ${{ github.workspace }}/upload-api
         
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build application package with Maven
        run: mvn -B package -DskipTests
        working-directory: ${{ github.workspace }}/upload-api

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: framedrop-upload-app-jar
          path: ${{ github.workspace }}/upload-api/target/*.jar

  docker-build:
    needs: [test, sonar,build]
    uses: ./.github/workflows/ecr.yml
    secrets: inherit

  deploy_ecs:
    needs: docker-build
    uses: ./.github/workflows/ecs.yml
    secrets: inherit
    with:
      image_uri: ${{ needs.docker-build.outputs.image_uri }}